-- Insert Programs Data for Smile Development Foundation
-- This file contains INSERT statements for all programs from the text file
-- Note: Make sure the programs table exists before running these queries
-- Run the create_programs_table.sql script first if needed

BEGIN;

-- Program 1: Orphan Sponsorship Programs
INSERT INTO programs (
    title_en,
    title_ar,
    description_en,
    description_ar,
    about_en,
    about_ar,
    goals_en,
    goals_ar,
    icon,
    color,
    implementation_location_en,
    implementation_location_ar,
    featured_image_url,
    slug_en,
    slug_ar,
    keywords_en,
    keywords_ar,
    tags_en,
    tags_ar,
    statics,
    funding_providers,
    donors,
    partners,
    slides,
    is_published,
    published_at
) VALUES (
    'Orphan Sponsorship Programs',
    'برامج كفالة فاقدي المعيل (الأيتام)',
    'These programs aim to provide financial and psychological support to orphans who have lost their breadwinner, focusing on meeting their basic needs and enhancing their educational opportunities. These programs also aim to improve the quality of life of orphans and provide the necessary support to ensure a bright future for them.',
    'تهدف هذه البرامج إلى تقديم الدعم المالي والنفسي للأيتام، حيث يركز على تلبية احتياجاتهم الأساسية وتعزيز فرص تعليمهم. كما تهدف إلى تحسين جودة حياة الأيتام وتوفير الدعم اللازم لضمان مستقبل مشرق لهم.',
    'Our orphan sponsorship program provides comprehensive support to children who have lost their primary caregivers. We focus on creating sustainable support systems that address immediate needs while building long-term opportunities for success.',
    'يوفر برنامج كفالة الأيتام الخاص بنا دعماً شاملاً للأطفال الذين فقدوا معيليهم الأساسيين. نحن نركز على إنشاء أنظمة دعم مستدامة تلبي الاحتياجات الفورية بينما تبني فرصاً طويلة المدى للنجاح.',
    ARRAY['Provide monthly financial support to orphaned children', 'Ensure access to quality education and healthcare', 'Offer psychological and social support services', 'Create mentorship programs for personal development', 'Establish emergency fund for urgent needs'],
    ARRAY['تقديم الدعم المالي الشهري للأطفال الأيتام', 'ضمان الوصول إلى التعليم والرعاية الصحية الجيدة', 'تقديم خدمات الدعم النفسي والاجتماعي', 'إنشاء برامج الإرشاد للتنمية الشخصية', 'إنشاء صندوق طوارئ للاحتياجات العاجلة'],
    'heart',
    '#E74C3C',
    'Yemen - Multiple Governorates',
    'اليمن - محافظات متعددة',
    '/assets/mockimage.jpg',
    'orphan-sponsorship-programs',
    'برامج-كفالة-فاقدي-المعيل-الايتام',
    ARRAY['orphans', 'sponsorship', 'children', 'support', 'education', 'healthcare'],
    ARRAY['أيتام', 'كفالة', 'أطفال', 'دعم', 'تعليم', 'رعاية صحية'],
    ARRAY['orphans', 'children', 'sponsorship'],
    ARRAY['أيتام', 'أطفال', 'كفالة'],
    '[{"titleEn": "Children Sponsored", "titleAr": "الأطفال المكفولين", "value": 850}, {"titleEn": "Monthly Support Amount", "titleAr": "مبلغ الدعم الشهري", "value": 50}, {"titleEn": "Years of Operation", "titleAr": "سنوات العمل", "value": 8}]',
    '[{"nameEn": "UNICEF", "nameAr": "اليونيسف", "imageUrl": "/assets/mocklogo.png"}, {"nameEn": "Islamic Development Bank", "nameAr": "البنك الإسلامي للتنمية", "imageUrl": "/assets/mocklogo.png"}]',
    '[{"nameEn": "Community Donors Network", "nameAr": "شبكة المتبرعين المجتمعيين", "imageUrl": "/assets/mocklogo.png"}, {"nameEn": "Global Child Welfare Fund", "nameAr": "صندوق رعاية الطفل العالمي", "imageUrl": "/assets/mocklogo.png"}]',
    '[{"nameEn": "Ministry of Social Affairs", "nameAr": "وزارة الشؤون الاجتماعية", "imageUrl": "/assets/mocklogo.png"}, {"nameEn": "Local Orphanages Network", "nameAr": "شبكة دور الأيتام المحلية", "imageUrl": "/assets/mocklogo.png"}]',
    '[{"titleEn": "Monthly Support Distribution", "titleAr": "توزيع الدعم الشهري", "imageUrl": "/assets/mockimage.jpg"}, {"titleEn": "Educational Support Activities", "titleAr": "أنشطة الدعم التعليمي", "imageUrl": "/assets/mockimage.jpg"}]',
    true,
    NOW()
);

-- Program 2: Orphans Entertainment Programs
INSERT INTO programs (
    title_en,
    title_ar,
    description_en,
    description_ar,
    about_en,
    about_ar,
    goals_en,
    goals_ar,
    icon,
    color,
    implementation_location_en,
    implementation_location_ar,
    featured_image_url,
    slug_en,
    slug_ar,
    keywords_en,
    keywords_ar,
    tags_en,
    tags_ar,
    statics,
    funding_providers,
    donors,
    partners,
    slides,
    is_published,
    published_at
) VALUES (
    'Orphans Entertainment Programs',
    'البرامج الترفيهية للأيتام',
    'These programs aim to provide recreational and entertainment opportunities for orphans, by organizing recreational activities and entertainment trips that enhance their social and psychological skills and enhance their sense of belonging and happiness.',
    'تهدف هذه البرامج إلى توفير فرص ترفيهية وتسلية للأيتام، من خلال تنظيم أنشطة ترفيهية ورحلات ترفيهية تعزز مهاراتهم الاجتماعية والنفسية وتعزز شعورهم بالانتماء والسعادة.',
    'Our entertainment programs for orphans focus on creating joyful experiences that promote healing, social development, and emotional well-being. We believe that play and recreation are essential for healthy childhood development.',
    'تركز برامجنا الترفيهية للأيتام على خلق تجارب مفرحة تعزز الشفاء والتنمية الاجتماعية والرفاهية العاطفية. نحن نؤمن أن اللعب والترفيه ضروريان للتنمية الصحية للطفولة.',
    ARRAY['Organize monthly recreational activities and outings', 'Develop social and interpersonal skills through group activities', 'Provide emotional healing through play therapy', 'Create positive memories and experiences', 'Build confidence and self-esteem'],
    ARRAY['تنظيم أنشطة ترفيهية ونزهات شهرية', 'تطوير المهارات الاجتماعية والشخصية من خلال الأنشطة الجماعية', 'توفير الشفاء العاطفي من خلال العلاج باللعب', 'خلق ذكريات وتجارب إيجابية', 'بناء الثقة وتقدير الذات'],
    'smile',
    '#F39C12',
    'Yemen - Multiple Cities',
    'اليمن - مدن متعددة',
    '/assets/mockimage.jpg',
    'orphans-entertainment-programs',
    'البرامج-الترفيهية-للايتام',
    ARRAY['entertainment', 'recreation', 'orphans', 'activities', 'trips', 'social skills'],
    ARRAY['ترفيه', 'تسلية', 'أيتام', 'أنشطة', 'رحلات', 'مهارات اجتماعية'],
    ARRAY['entertainment', 'recreation', 'orphans'],
    ARRAY['ترفيه', 'تسلية', 'أيتام'],
    '[{"titleEn": "Children Participated", "titleAr": "الأطفال المشاركين", "value": 1200}, {"titleEn": "Activities Organized", "titleAr": "الأنشطة المنظمة", "value": 96}, {"titleEn": "Entertainment Trips", "titleAr": "الرحلات الترفيهية", "value": 24}]',
    '[{"nameEn": "Children Recreation Fund", "nameAr": "صندوق ترفيه الأطفال", "imageUrl": "/assets/mocklogo.png"}, {"nameEn": "Youth Development Initiative", "nameAr": "مبادرة تنمية الشباب", "imageUrl": "/assets/mocklogo.png"}]',
    '[{"nameEn": "Happy Children Foundation", "nameAr": "مؤسسة الأطفال السعداء", "imageUrl": "/assets/mocklogo.png"}, {"nameEn": "Entertainment for All", "nameAr": "الترفيه للجميع", "imageUrl": "/assets/mocklogo.png"}]',
    '[{"nameEn": "Local Recreation Centers", "nameAr": "مراكز الترفيه المحلية", "imageUrl": "/assets/mocklogo.png"}, {"nameEn": "Community Volunteers", "nameAr": "المتطوعون المجتمعيون", "imageUrl": "/assets/mocklogo.png"}]',
    '[{"titleEn": "Fun Day Activities", "titleAr": "أنشطة يوم المرح", "imageUrl": "/assets/mockimage.jpg"}, {"titleEn": "Educational Trips", "titleAr": "الرحلات التعليمية", "imageUrl": "/assets/mockimage.jpg"}]',
    true,
    NOW()
);

-- Program 3: Women Educational and Rehabilitation Programs
INSERT INTO programs (
    title_en,
    title_ar,
    description_en,
    description_ar,
    about_en,
    about_ar,
    goals_en,
    goals_ar,
    icon,
    color,
    implementation_location_en,
    implementation_location_ar,
    featured_image_url,
    slug_en,
    slug_ar,
    keywords_en,
    keywords_ar,
    tags_en,
    tags_ar,
    statics,
    funding_providers,
    donors,
    partners,
    slides,
    is_published,
    published_at
) VALUES (
    'Women Educational and Rehabilitation Programs',
    'البرامج التثقيفية والتأهيلية للمرأة',
    'These programmes aim to provide educational and cultural opportunities for women, including vocational training and rehabilitation programmes, workshops and educational courses, with the aim of empowering them and enhancing their capabilities and economic opportunities.',
    'تهدف هذه البرامج إلى توفير فرص تعليمية وتثقيفية للنساء، بما في ذلك برامج التدريب والتأهيل المهني، وورش العمل والدورات التعليمية، بهدف تمكينهن وتعزيز قدراتهن وفرصهن الاقتصادية.',
    'Our women empowerment programs are designed to break barriers and create pathways for women to achieve economic independence and personal growth. We provide comprehensive training and support systems.',
    'صُممت برامج تمكين المرأة لدينا لكسر الحواجز وخلق مسارات للنساء لتحقيق الاستقلال الاقتصادي والنمو الشخصي. نحن نوفر برامج تدريب وأنظمة دعم شاملة.',
    ARRAY['Provide vocational training in various fields', 'Enhance literacy and basic education skills', 'Develop entrepreneurship and business skills', 'Create income-generating opportunities', 'Build confidence and leadership abilities'],
    ARRAY['توفير التدريب المهني في مجالات مختلفة', 'تعزيز مهارات القراءة والكتابة والتعليم الأساسي', 'تطوير مهارات ريادة الأعمال والأعمال التجارية', 'خلق فرص لتوليد الدخل', 'بناء الثقة وقدرات القيادة'],
    'users',
    '#9B59B6',
    'Yemen - Urban and Rural Areas',
    'اليمن - المناطق الحضرية والريفية',
    '/assets/mockimage.jpg',
    'women-educational-rehabilitation-programs',
    'البرامج-التثقيفية-والتاهيلية-للمراة',
    ARRAY['women', 'education', 'empowerment', 'vocational training', 'rehabilitation', 'economic opportunities'],
    ARRAY['المرأة', 'تعليم', 'تمكين', 'تدريب مهني', 'تأهيل', 'فرص اقتصادية'],
    ARRAY['women', 'education', 'empowerment'],
    ARRAY['المرأة', 'تعليم', 'تمكين'],
    '[{"titleEn": "Women Trained", "titleAr": "النساء المدربات", "value": 650}, {"titleEn": "Training Programs", "titleAr": "برامج التدريب", "value": 45}, {"titleEn": "Success Rate", "titleAr": "معدل النجاح", "value": 87}]',
    '[{"nameEn": "UN Women", "nameAr": "هيئة الأمم المتحدة للمرأة", "imageUrl": "/assets/mocklogo.png"}, {"nameEn": "World Bank", "nameAr": "البنك الدولي", "imageUrl": "/assets/mocklogo.png"}]',
    '[{"nameEn": "Women Empowerment Fund", "nameAr": "صندوق تمكين المرأة", "imageUrl": "/assets/mocklogo.png"}, {"nameEn": "Gender Equality Initiative", "nameAr": "مبادرة المساواة بين الجنسين", "imageUrl": "/assets/mocklogo.png"}]',
    '[{"nameEn": "Ministry of Education", "nameAr": "وزارة التربية والتعليم", "imageUrl": "/assets/mocklogo.png"}, {"nameEn": "Women Business Network", "nameAr": "شبكة أعمال المرأة", "imageUrl": "/assets/mocklogo.png"}]',
    '[{"titleEn": "Vocational Training Sessions", "titleAr": "جلسات التدريب المهني", "imageUrl": "/assets/mockimage.jpg"}, {"titleEn": "Women Graduation Ceremony", "titleAr": "حفل تخرج النساء", "imageUrl": "/assets/mockimage.jpg"}]',
    true,
    NOW()
);

-- Program 4: Youth Rehabilitation and Empowerment Programs
INSERT INTO programs (
    title_en,
    title_ar,
    description_en,
    description_ar,
    about_en,
    about_ar,
    goals_en,
    goals_ar,
    icon,
    color,
    implementation_location_en,
    implementation_location_ar,
    featured_image_url,
    slug_en,
    slug_ar,
    keywords_en,
    keywords_ar,
    tags_en,
    tags_ar,
    statics,
    funding_providers,
    donors,
    partners,
    slides,
    is_published,
    published_at
) VALUES (
    'Youth Rehabilitation and Empowerment Programs',
    'برامج التأهيل والتمكين للشباب',
    'These programmes target young people and aim to develop their personal and professional skills through training and guidance programmes, and provide job opportunities and youth projects, with the aim of enabling them to achieve their ambitions and improve their future.',
    'تستهدف هذه البرامج الشباب وتهدف إلى تطوير مهاراتهم الشخصية والمهنية من خلال برامج التدريب والتوجيه، وتوفير فرص العمل والمشاريع الشبابية، بهدف تمكينهم من تحقيق طموحاتهم وتحسين مستقبلهم.',
    'Our youth programs focus on transforming young lives by providing the tools, skills, and opportunities needed to build successful careers and contribute meaningfully to society.',
    'تركز برامج الشباب لدينا على تحويل حياة الشباب من خلال توفير الأدوات والمهارات والفرص اللازمة لبناء مهن ناجحة والمساهمة بطريقة مفيدة في المجتمع.',
    ARRAY['Develop technical and soft skills', 'Provide career guidance and mentorship', 'Create job placement opportunities', 'Support youth entrepreneurship initiatives', 'Build leadership and communication abilities'],
    ARRAY['تطوير المهارات التقنية والشخصية', 'توفير التوجيه المهني والإرشاد', 'خلق فرص التوظيف', 'دعم مبادرات ريادة الأعمال الشبابية', 'بناء قدرات القيادة والتواصل'],
    'trending-up',
    '#3498DB',
    'Yemen - Major Cities',
    'اليمن - المدن الرئيسية',
    '/assets/mockimage.jpg',
    'youth-rehabilitation-empowerment-programs',
    'برامج-التاهيل-والتمكين-للشباب',
    ARRAY['youth', 'empowerment', 'skills development', 'job opportunities', 'entrepreneurship', 'training'],
    ARRAY['الشباب', 'تمكين', 'تطوير المهارات', 'فرص عمل', 'ريادة أعمال', 'تدريب'],
    ARRAY['youth', 'empowerment', 'skills'],
    ARRAY['الشباب', 'تمكين', 'مهارات'],
    '[{"titleEn": "Youth Participants", "titleAr": "المشاركين من الشباب", "value": 980}, {"titleEn": "Job Placements", "titleAr": "فرص التوظيف", "value": 456}, {"titleEn": "Training Hours", "titleAr": "ساعات التدريب", "value": 15600}]',
    '[{"nameEn": "Youth Employment Agency", "nameAr": "وكالة توظيف الشباب", "imageUrl": "/assets/mocklogo.png"}, {"nameEn": "Skills Development Fund", "nameAr": "صندوق تنمية المهارات", "imageUrl": "/assets/mocklogo.png"}]',
    '[{"nameEn": "Future Leaders Foundation", "nameAr": "مؤسسة قادة المستقبل", "imageUrl": "/assets/mocklogo.png"}, {"nameEn": "Youth Success Network", "nameAr": "شبكة نجاح الشباب", "imageUrl": "/assets/mocklogo.png"}]',
    '[{"nameEn": "Ministry of Youth and Sports", "nameAr": "وزارة الشباب والرياضة", "imageUrl": "/assets/mocklogo.png"}, {"nameEn": "Private Sector Companies", "nameAr": "شركات القطاع الخاص", "imageUrl": "/assets/mocklogo.png"}]',
    '[{"titleEn": "Skills Training Workshop", "titleAr": "ورشة تدريب المهارات", "imageUrl": "/assets/mockimage.jpg"}, {"titleEn": "Youth Employment Fair", "titleAr": "معرض توظيف الشباب", "imageUrl": "/assets/mockimage.jpg"}]',
    true,
    NOW()
);

-- Program 5: Emergency Food Projects
INSERT INTO programs (
    title_en,
    title_ar,
    description_en,
    description_ar,
    about_en,
    about_ar,
    goals_en,
    goals_ar,
    icon,
    color,
    implementation_location_en,
    implementation_location_ar,
    featured_image_url,
    slug_en,
    slug_ar,
    keywords_en,
    keywords_ar,
    tags_en,
    tags_ar,
    statics,
    funding_providers,
    donors,
    partners,
    slides,
    is_published,
    published_at
) VALUES (
    'Emergency Food Projects',
    'المشاريع الغذائية الطارئة',
    'The Foundation provides emergency food projects for displaced persons and people affected by disasters, by distributing food and providing the necessary food assistance to meet their basic needs.',
    'تقدم المؤسسة مشاريع غذائية طارئة للنازحين والأشخاص المتضررين من الكوارث، من خلال توزيع الطعام وتوفير المساعدة الغذائية الضرورية لتلبية احتياجاتهم الأساسية.',
    'Our emergency food projects provide critical nutrition support to vulnerable populations during times of crisis, ensuring no one goes hungry when disaster strikes.',
    'توفر مشاريع الطعام الطارئة لدينا دعماً غذائياً حيوياً للسكان المعرضين للخطر في أوقات الأزمات، مما يضمن عدم معاناة أحد من الجوع عند وقوع الكوارث.',
    ARRAY['Provide immediate food assistance during emergencies', 'Distribute nutritious food packages to displaced families', 'Establish emergency feeding centers', 'Coordinate with relief organizations', 'Monitor nutritional status of beneficiaries'],
    ARRAY['توفير المساعدة الغذائية الفورية أثناء الطوارئ', 'توزيع طرود غذائية مغذية للعائلات النازحة', 'إنشاء مراكز إطعام طارئة', 'التنسيق مع منظمات الإغاثة', 'مراقبة الحالة الغذائية للمستفيدين'],
    'package',
    '#E67E22',
    'Yemen - Conflict and Disaster Areas',
    'اليمن - مناطق النزاع والكوارث',
    '/assets/mockimage.jpg',
    'emergency-food-projects',
    'المشاريع-الغذائية-الطارئة',
    ARRAY['emergency', 'food assistance', 'displaced persons', 'disaster relief', 'nutrition', 'humanitarian aid'],
    ARRAY['طوارئ', 'مساعدة غذائية', 'نازحين', 'إغاثة كوارث', 'تغذية', 'مساعدة إنسانية'],
    ARRAY['emergency', 'food', 'relief'],
    ARRAY['طوارئ', 'غذاء', 'إغاثة'],
    '[{"titleEn": "Families Assisted", "titleAr": "العائلات المساعدة", "value": 5200}, {"titleEn": "Food Packages Distributed", "titleAr": "الطرود الغذائية الموزعة", "value": 18500}, {"titleEn": "Emergency Responses", "titleAr": "الاستجابات الطارئة", "value": 47}]',
    '[{"nameEn": "World Food Programme", "nameAr": "برنامج الغذاء العالمي", "imageUrl": "/assets/mocklogo.png"}, {"nameEn": "USAID", "nameAr": "الوكالة الأمريكية للتنمية الدولية", "imageUrl": "/assets/mocklogo.png"}]',
    '[{"nameEn": "Emergency Relief Fund", "nameAr": "صندوق الإغاثة الطارئة", "imageUrl": "/assets/mocklogo.png"}, {"nameEn": "Global Humanitarian Network", "nameAr": "الشبكة الإنسانية العالمية", "imageUrl": "/assets/mocklogo.png"}]',
    '[{"nameEn": "Local Relief Committees", "nameAr": "لجان الإغاثة المحلية", "imageUrl": "/assets/mocklogo.png"}, {"nameEn": "International Red Crescent", "nameAr": "الهلال الأحمر الدولي", "imageUrl": "/assets/mocklogo.png"}]',
    '[{"titleEn": "Food Distribution Centers", "titleAr": "مراكز توزيع الطعام", "imageUrl": "/assets/mockimage.jpg"}, {"titleEn": "Emergency Response Team", "titleAr": "فريق الاستجابة الطارئة", "imageUrl": "/assets/mockimage.jpg"}]',
    true,
    NOW()
);

-- Program 6: Health Projects
INSERT INTO programs (
    title_en,
    title_ar,
    description_en,
    description_ar,
    about_en,
    about_ar,
    goals_en,
    goals_ar,
    icon,
    color,
    implementation_location_en,
    implementation_location_ar,
    featured_image_url,
    slug_en,
    slug_ar,
    keywords_en,
    keywords_ar,
    tags_en,
    tags_ar,
    statics,
    funding_providers,
    donors,
    partners,
    slides,
    is_published,
    published_at
) VALUES (
    'Health Projects',
    'المشاريع الصحية',
    'The Foundation provides various health projects such as distributing hygiene kits, providing oxygen cylinders and medical treatments, and providing wheelchairs for people with special needs, with the aim of improving the health status and providing the necessary care for the target groups.',
    'تقدم المؤسسة مشاريع صحية متنوعة مثل توزيع حقائب النظافة الصحية، وتوفير اسطوانات الأكسجين والعلاجات الطبية وتوفير كراسي لذوي الاحتياجات الخاصة، بهدف تحسين الوضع الصحي وتوفير الرعاية اللازمة للفئات المستهدفة.',
    'Our health projects address critical healthcare gaps by providing essential medical supplies, equipment, and services to vulnerable communities, ensuring access to basic healthcare regardless of circumstances.',
    'تعالج مشاريعنا الصحية الثغرات الحيوية في الرعاية الصحية من خلال توفير الإمدادات الطبية والمعدات والخدمات الأساسية للمجتمعات المعرضة للخطر، مما يضمن الوصول إلى الرعاية الصحية الأساسية بغض النظر عن الظروف.',
    ARRAY['Distribute hygiene and sanitation kits', 'Provide medical equipment and oxygen cylinders', 'Supply wheelchairs and mobility aids', 'Offer medical treatments and consultations', 'Conduct health awareness campaigns'],
    ARRAY['توزيع مجموعات النظافة والصرف الصحي', 'توفير المعدات الطبية واسطوانات الأكسجين', 'توريد الكراسي المتحركة ومساعدات التنقل', 'تقديم العلاجات الطبية والاستشارات', 'إجراء حملات التوعية الصحية'],
    'heart-pulse',
    '#27AE60',
    'Yemen - Healthcare Facilities',
    'اليمن - المرافق الصحية',
    '/assets/mockimage.jpg',
    'health-projects',
    'المشاريع-الصحية',
    ARRAY['health', 'medical equipment', 'hygiene', 'oxygen cylinders', 'wheelchairs', 'healthcare access'],
    ARRAY['صحة', 'معدات طبية', 'نظافة', 'اسطوانات أكسجين', 'كراسي متحركة', 'وصول للرعاية الصحية'],
    ARRAY['health', 'medical', 'healthcare'],
    ARRAY['صحة', 'طبي', 'رعاية صحية'],
    '[{"titleEn": "Hygiene Kits Distributed", "titleAr": "مجموعات النظافة الموزعة", "value": 8900}, {"titleEn": "Oxygen Cylinders Provided", "titleAr": "اسطوانات الأكسجين المقدمة", "value": 340}, {"titleEn": "Wheelchairs Distributed", "titleAr": "الكراسي المتحركة الموزعة", "value": 156}]',
    '[{"nameEn": "World Health Organization", "nameAr": "منظمة الصحة العالمية", "imageUrl": "/assets/mocklogo.png"}, {"nameEn": "Doctors Without Borders", "nameAr": "أطباء بلا حدود", "imageUrl": "/assets/mocklogo.png"}]',
    '[{"nameEn": "Health for All Foundation", "nameAr": "مؤسسة الصحة للجميع", "imageUrl": "/assets/mocklogo.png"}, {"nameEn": "Medical Aid International", "nameAr": "المساعدة الطبية الدولية", "imageUrl": "/assets/mocklogo.png"}]',
    '[{"nameEn": "Ministry of Public Health", "nameAr": "وزارة الصحة العامة", "imageUrl": "/assets/mocklogo.png"}, {"nameEn": "Local Hospitals Network", "nameAr": "شبكة المستشفيات المحلية", "imageUrl": "/assets/mocklogo.png"}]',
    '[{"titleEn": "Medical Equipment Distribution", "titleAr": "توزيع المعدات الطبية", "imageUrl": "/assets/mockimage.jpg"}, {"titleEn": "Health Awareness Session", "titleAr": "جلسة التوعية الصحية", "imageUrl": "/assets/mockimage.jpg"}]',
    true,
    NOW()
);

-- Program 7: Adha Sacrifice Meat Projects
INSERT INTO programs (
    title_en,
    title_ar,
    description_en,
    description_ar,
    about_en,
    about_ar,
    goals_en,
    goals_ar,
    icon,
    color,
    implementation_location_en,
    implementation_location_ar,
    featured_image_url,
    slug_en,
    slug_ar,
    keywords_en,
    keywords_ar,
    tags_en,
    tags_ar,
    statics,
    funding_providers,
    donors,
    partners,
    slides,
    is_published,
    published_at
) VALUES (
    'Adha Sacrifice Meat Projects',
    'مشاريع الأضاحي',
    'The Foundation organizes and implements Adha sacrifice meat projects by distributing meat, cash donations, and Eid clothing to needy and displaced families and orphans, with the aim of meeting their needs and enhancing the social spirit and solidarity in society.',
    'تقوم المؤسسة بتنظيم وتنفيذ مشاريع الأضاحي من خلال توزيع اللحوم والصدقات النقدية وكسوة العيد على الأسر المحتاجة والنازحة والأيتام، بهدف تلبية احتياجاتهم وتعزيز الروح الاجتماعية والتكافل في المجتمع.',
    'Our Adha sacrifice meat projects embody the spirit of giving and sharing during Eid Al-Adha, ensuring that every family can participate in this blessed celebration regardless of their economic circumstances.',
    'تجسد مشاريع لحوم الأضاحي لدينا روح العطاء والمشاركة خلال عيد الأضحى، مما يضمن أن كل عائلة يمكنها المشاركة في هذا الاحتفال المبارك بغض النظر عن ظروفها الاقتصادية.',
    ARRAY['Distribute fresh meat to needy families during Eid Al-Adha', 'Provide cash assistance for Eid celebrations', 'Distribute Eid clothing to children and families', 'Promote social solidarity and community spirit', 'Ensure dignified celebration for all families'],
    ARRAY['توزيع اللحوم الطازجة للعائلات المحتاجة أثناء عيد الأضحى', 'تقديم المساعدة النقدية لاحتفالات العيد', 'توزيع ملابس العيد للأطفال والعائلات', 'تعزيز التضامن الاجتماعي وروح المجتمع', 'ضمان احتفال كريم لجميع العائلات'],
    'gift',
    '#8E44AD',
    'Yemen - All Governorates',
    'اليمن - جميع المحافظات',
    '/assets/mockimage.jpg',
    'adha-sacrifice-meat-projects',
    'مشاريع-الاضاحي',
    ARRAY['Eid Al-Adha', 'sacrifice meat', 'religious celebration', 'meat distribution', 'Eid clothing', 'social solidarity'],
    ARRAY['عيد الأضحى', 'لحوم الأضاحي', 'احتفال ديني', 'توزيع اللحوم', 'كسوة العيد', 'تضامن اجتماعي'],
    ARRAY['Eid', 'sacrifice', 'religious'],
    ARRAY['عيد', 'أضاحي', 'ديني'],
    '[{"titleEn": "Families Benefited", "titleAr": "العائلات المستفيدة", "value": 3800}, {"titleEn": "Meat Packages Distributed", "titleAr": "طرود اللحوم الموزعة", "value": 3800}, {"titleEn": "Eid Clothing Sets", "titleAr": "مجموعات ملابس العيد", "value": 2100}]',
    '[{"nameEn": "Islamic Relief Organization", "nameAr": "منظمة الإغاثة الإسلامية", "imageUrl": "/assets/mocklogo.png"}, {"nameEn": "Religious Affairs Ministry", "nameAr": "وزارة الشؤون الدينية", "imageUrl": "/assets/mocklogo.png"}]',
    '[{"nameEn": "Eid Celebration Fund", "nameAr": "صندوق احتفالات العيد", "imageUrl": "/assets/mocklogo.png"}, {"nameEn": "Community Generosity Network", "nameAr": "شبكة الكرم المجتمعي", "imageUrl": "/assets/mocklogo.png"}]',
    '[{"nameEn": "Local Mosques Committee", "nameAr": "لجنة المساجد المحلية", "imageUrl": "/assets/mocklogo.png"}, {"nameEn": "Religious Scholars Council", "nameAr": "مجلس العلماء الدينيين", "imageUrl": "/assets/mocklogo.png"}]',
    '[{"titleEn": "Meat Distribution Event", "titleAr": "فعالية توزيع اللحوم", "imageUrl": "/assets/mockimage.jpg"}, {"titleEn": "Eid Celebration with Families", "titleAr": "احتفال العيد مع العائلات", "imageUrl": "/assets/mockimage.jpg"}]',
    true,
    NOW()
);

-- Program 8: Shelter Projects
INSERT INTO programs (
    title_en,
    title_ar,
    description_en,
    description_ar,
    about_en,
    about_ar,
    goals_en,
    goals_ar,
    icon,
    color,
    implementation_location_en,
    implementation_location_ar,
    featured_image_url,
    slug_en,
    slug_ar,
    keywords_en,
    keywords_ar,
    tags_en,
    tags_ar,
    statics,
    funding_providers,
    donors,
    partners,
    slides,
    is_published,
    published_at
) VALUES (
    'Shelter Projects',
    'المشاريع الإيوائية',
    'The Foundation is concerned with providing shelter for orphans and the affected, by building and providing air conditioners and using solar energy to provide electricity, in addition to providing home furniture to ensure a suitable and safe environment for the beneficiaries and improving their living conditions.',
    'تهتم المؤسسة بتوفير مأوى للأيتام والمتضررين من خلال بناء وتوفير المكيفات واستخدام الطاقة الشمسية لتوفير الكهرباء، بالإضافة إلى توفير الأثاث المنزلي لضمان توفير بيئة ملائمة وآمنة للمستفيدين وتحسين ظروف حياتهم.',
    'Our shelter projects provide more than just a roof over people''s heads - we create homes that offer dignity, safety, and comfort with sustainable energy solutions and complete furnishing.',
    'توفر مشاريع الإيواء لدينا أكثر من مجرد سقف فوق رؤوس الناس - نحن ننشئ منازل توفر الكرامة والأمان والراحة مع حلول الطاقة المستدامة والتأثيث الكامل.',
    ARRAY['Build safe and dignified housing units', 'Install solar energy systems for sustainable electricity', 'Provide air conditioning for comfortable living', 'Furnish homes with essential furniture and appliances', 'Create community spaces for social interaction'],
    ARRAY['بناء وحدات سكنية آمنة وكريمة', 'تركيب أنظمة الطاقة الشمسية للكهرباء المستدامة', 'توفير أجهزة التكييف للعيش المريح', 'تأثيث المنازل بالأثاث والأجهزة الأساسية', 'إنشاء مساحات مجتمعية للتفاعل الاجتماعي'],
    'home',
    '#16A085',
    'Yemen - Displacement Areas',
    'اليمن - مناطق النزوح',
    '/assets/mockimage.jpg',
    'shelter-projects',
    'المشاريع-الايوائية',
    ARRAY['shelter', 'housing', 'solar energy', 'air conditioning', 'furniture', 'displaced persons', 'orphans'],
    ARRAY['مأوى', 'إسكان', 'طاقة شمسية', 'تكييف', 'أثاث', 'نازحين', 'أيتام'],
    ARRAY['shelter', 'housing', 'solar'],
    ARRAY['مأوى', 'إسكان', 'شمسي'],
    '[{"titleEn": "Housing Units Built", "titleAr": "الوحدات السكنية المبنية", "value": 89}, {"titleEn": "Solar Systems Installed", "titleAr": "أنظمة الطاقة الشمسية المركبة", "value": 89}, {"titleEn": "Families Housed", "titleAr": "العائلات المسكنة", "value": 356}]',
    '[{"nameEn": "UN Habitat", "nameAr": "برنامج الأمم المتحدة للمستوطنات البشرية", "imageUrl": "/assets/mocklogo.png"}, {"nameEn": "Solar Energy Foundation", "nameAr": "مؤسسة الطاقة الشمسية", "imageUrl": "/assets/mocklogo.png"}]',
    '[{"nameEn": "Homes for All Initiative", "nameAr": "مبادرة المنازل للجميع", "imageUrl": "/assets/mocklogo.png"}, {"nameEn": "Sustainable Living Fund", "nameAr": "صندوق المعيشة المستدامة", "imageUrl": "/assets/mocklogo.png"}]',
    '[{"nameEn": "Ministry of Housing", "nameAr": "وزارة الإسكان", "imageUrl": "/assets/mocklogo.png"}, {"nameEn": "Construction Companies Alliance", "nameAr": "تحالف شركات البناء", "imageUrl": "/assets/mocklogo.png"}]',
    '[{"titleEn": "New Housing Complex", "titleAr": "مجمع الإسكان الجديد", "imageUrl": "/assets/mockimage.jpg"}, {"titleEn": "Solar Panel Installation", "titleAr": "تركيب الألواح الشمسية", "imageUrl": "/assets/mockimage.jpg"}]',
    true,
    NOW()
);

COMMIT;
