-- Migration: create_table_news
-- Type: TABLE
-- Command for AI Assistant:
-- call_mcp_tool apply_migration
-- name: create_table_news
-- query: CREATE TABLE "news" (
	"id" serial PRIMARY KEY NOT NULL,
	"is_english" boolean DEFAULT false,
	"is_arabic" boolean DEFAULT false,
	"include_in_sitemap_en" boolean DEFAULT true,
	"include_in_sitemap_ar" boolean DEFAULT true,
	"title_en" varchar(500) NOT NULL,
	"title_ar" varchar(500) NOT NULL,
	"featured_image_url" varchar(1000) NOT NULL,
	"other_images_url" text[] DEFAULT '{}',
	"content_en" text NOT NULL,
	"content_ar" text NOT NULL,
	"category_id" bigint,
	"program_id" bigint,
	"project_id" bigint,
	"activity_id" bigint,
	"slug_en" varchar(200) NOT NULL,
	"slug_ar" varchar(200) NOT NULL,
	"keywords_en" text[] DEFAULT '{}',
	"keywords_ar" text[] DEFAULT '{}',
	"tags_en" text[] DEFAULT '{}',
	"tags_ar" text[] DEFAULT '{}',
	"read_time" integer DEFAULT 0,
	"page_views" integer DEFAULT 0,
	"author_id" uuid NOT NULL,
	"is_published" boolean DEFAULT false,
	"published_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now(),
	CONSTRAINT "news_slug_en_unique" UNIQUE("slug_en"),
	CONSTRAINT "news_slug_ar_unique" UNIQUE("slug_ar")
);

CREATE TABLE "news" (
	"id" serial PRIMARY KEY NOT NULL,
	"is_english" boolean DEFAULT false,
	"is_arabic" boolean DEFAULT false,
	"include_in_sitemap_en" boolean DEFAULT true,
	"include_in_sitemap_ar" boolean DEFAULT true,
	"title_en" varchar(500) NOT NULL,
	"title_ar" varchar(500) NOT NULL,
	"featured_image_url" varchar(1000) NOT NULL,
	"other_images_url" text[] DEFAULT '{}',
	"content_en" text NOT NULL,
	"content_ar" text NOT NULL,
	"category_id" bigint,
	"program_id" bigint,
	"project_id" bigint,
	"activity_id" bigint,
	"slug_en" varchar(200) NOT NULL,
	"slug_ar" varchar(200) NOT NULL,
	"keywords_en" text[] DEFAULT '{}',
	"keywords_ar" text[] DEFAULT '{}',
	"tags_en" text[] DEFAULT '{}',
	"tags_ar" text[] DEFAULT '{}',
	"read_time" integer DEFAULT 0,
	"page_views" integer DEFAULT 0,
	"author_id" uuid NOT NULL,
	"is_published" boolean DEFAULT false,
	"published_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now(),
	CONSTRAINT "news_slug_en_unique" UNIQUE("slug_en"),
	CONSTRAINT "news_slug_ar_unique" UNIQUE("slug_ar")
);