-- Migration: create_table_success_stories
-- Type: TABLE
-- Command for AI Assistant:
-- call_mcp_tool apply_migration
-- name: create_table_success_stories
-- query: CREATE TABLE "success_stories" (
	"id" serial PRIMARY KEY NOT NULL,
	"is_english" boolean DEFAULT false,
	"is_arabic" boolean DEFAULT false,
	"title_en" varchar(500) NOT NULL,
	"title_ar" varchar(500) NOT NULL,
	"featured_image_url" varchar(1000) NOT NULL,
	"video" varchar(1000) NOT NULL,
	"program_id" bigint,
	"person_name_en" varchar(200) NOT NULL,
	"person_name_ar" varchar(200) NOT NULL,
	"person_age" integer NOT NULL,
	"person_location_en" varchar(200) NOT NULL,
	"person_location_ar" varchar(200) NOT NULL,
	"city_en" varchar(200) NOT NULL,
	"city_ar" varchar(200) NOT NULL,
	"other_images_url" text[] DEFAULT '{}',
	"content_en" text NOT NULL,
	"content_ar" text NOT NULL,
	"slug_en" varchar(200) NOT NULL,
	"slug_ar" varchar(200) NOT NULL,
	"keywords_en" text[] DEFAULT '{}',
	"keywords_ar" text[] DEFAULT '{}',
	"tags_en" text[] DEFAULT '{}',
	"tags_ar" text[] DEFAULT '{}',
	"read_time" integer DEFAULT 0,
	"page_views" integer DEFAULT 0,
	"is_published" boolean DEFAULT false,
	"published_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now(),
	CONSTRAINT "success_stories_slug_en_unique" UNIQUE("slug_en"),
	CONSTRAINT "success_stories_slug_ar_unique" UNIQUE("slug_ar")
);

CREATE TABLE "success_stories" (
	"id" serial PRIMARY KEY NOT NULL,
	"is_english" boolean DEFAULT false,
	"is_arabic" boolean DEFAULT false,
	"title_en" varchar(500) NOT NULL,
	"title_ar" varchar(500) NOT NULL,
	"featured_image_url" varchar(1000) NOT NULL,
	"video" varchar(1000) NOT NULL,
	"program_id" bigint,
	"person_name_en" varchar(200) NOT NULL,
	"person_name_ar" varchar(200) NOT NULL,
	"person_age" integer NOT NULL,
	"person_location_en" varchar(200) NOT NULL,
	"person_location_ar" varchar(200) NOT NULL,
	"city_en" varchar(200) NOT NULL,
	"city_ar" varchar(200) NOT NULL,
	"other_images_url" text[] DEFAULT '{}',
	"content_en" text NOT NULL,
	"content_ar" text NOT NULL,
	"slug_en" varchar(200) NOT NULL,
	"slug_ar" varchar(200) NOT NULL,
	"keywords_en" text[] DEFAULT '{}',
	"keywords_ar" text[] DEFAULT '{}',
	"tags_en" text[] DEFAULT '{}',
	"tags_ar" text[] DEFAULT '{}',
	"read_time" integer DEFAULT 0,
	"page_views" integer DEFAULT 0,
	"is_published" boolean DEFAULT false,
	"published_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now(),
	CONSTRAINT "success_stories_slug_en_unique" UNIQUE("slug_en"),
	CONSTRAINT "success_stories_slug_ar_unique" UNIQUE("slug_ar")
);