CREATE TABLE "programs" (
	"id" serial PRIMARY KEY NOT NULL,
	"title_en" varchar(500) NOT NULL,
	"title_ar" varchar(500) NOT NULL,
	"description_en" text NOT NULL,
	"description_ar" text NOT NULL,
	"about_en" text,
	"about_ar" text,
	"goals_en" text[],
	"goals_ar" text[],
	"statics" jsonb DEFAULT '[]'::jsonb,
	"icon" varchar(100),
	"color" varchar(20),
	"implementation_location_en" varchar(500),
	"implementation_location_ar" varchar(500),
	"funding_providers" jsonb DEFAULT '[]'::jsonb,
	"donors" jsonb DEFAULT '[]'::jsonb,
	"partners" jsonb DEFAULT '[]'::jsonb,
	"featured_image_url" varchar(1000),
	"slides" jsonb DEFAULT '[]'::jsonb,
	"slug_en" varchar(200) NOT NULL,
	"slug_ar" varchar(200) NOT NULL,
	"keywords_en" text[],
	"keywords_ar" text[],
	"tags_en" text[],
	"tags_ar" text[],
	"include_in_sitemap_en" boolean DEFAULT true,
	"include_in_sitemap_ar" boolean DEFAULT true,
	"page_views" integer DEFAULT 0,
	"created_by" uuid,
	"is_published" boolean DEFAULT false,
	"published_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now(),
	CONSTRAINT "programs_slug_en_unique" UNIQUE("slug_en"),
	CONSTRAINT "programs_slug_ar_unique" UNIQUE("slug_ar")
);
--> statement-breakpoint
CREATE TABLE "projects" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"is_english" boolean DEFAULT true NOT NULL,
	"is_arabic" boolean DEFAULT true NOT NULL,
	"title_en" text NOT NULL,
	"title_ar" text NOT NULL,
	"description_en" text NOT NULL,
	"description_ar" text NOT NULL,
	"featured_image_url" text NOT NULL,
	"color" text DEFAULT '#000000' NOT NULL,
	"video_url" text,
	"banners" jsonb DEFAULT '[]'::jsonb,
	"goals_en" text[] DEFAULT '{}',
	"goals_ar" text[] DEFAULT '{}',
	"statics" jsonb DEFAULT '[]'::jsonb,
	"funding_providers" jsonb DEFAULT '[]'::jsonb,
	"donors" jsonb DEFAULT '[]'::jsonb,
	"partners" jsonb DEFAULT '[]'::jsonb,
	"deliverables" jsonb DEFAULT '[]'::jsonb,
	"resources" jsonb DEFAULT '[]'::jsonb,
	"cost" jsonb DEFAULT '[]'::jsonb,
	"beneficiaries" jsonb DEFAULT '[]'::jsonb,
	"slug_en" text NOT NULL,
	"slug_ar" text NOT NULL,
	"keywords_en" text[] DEFAULT '{}',
	"keywords_ar" text[] DEFAULT '{}',
	"tags_en" text[] DEFAULT '{}',
	"tags_ar" text[] DEFAULT '{}',
	"page_views" bigint DEFAULT 0,
	"program_id" bigint,
	"category_id" bigint,
	"activity_ids" bigint[] DEFAULT '{}',
	"is_published" boolean DEFAULT false,
	"published_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now(),
	CONSTRAINT "projects_slug_en_unique" UNIQUE("slug_en"),
	CONSTRAINT "projects_slug_ar_unique" UNIQUE("slug_ar")
);
--> statement-breakpoint
CREATE TABLE "videos" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"title_en" text NOT NULL,
	"title_ar" text NOT NULL,
	"description_en" text,
	"description_ar" text,
	"mime_type" text DEFAULT 'video/mp4' NOT NULL,
	"size" bigint NOT NULL,
	"width" integer NOT NULL,
	"height" integer NOT NULL,
	"url" text NOT NULL,
	"location_en" text,
	"location_ar" text,
	"is_public" boolean DEFAULT true NOT NULL,
	"category_id" bigint,
	"slug_en" text NOT NULL,
	"slug_ar" text NOT NULL,
	"keywords_en" text[] DEFAULT '{}',
	"keywords_ar" text[] DEFAULT '{}',
	"tags_en" text[] DEFAULT '{}',
	"tags_ar" text[] DEFAULT '{}',
	"views" bigint DEFAULT 0,
	"is_published" boolean DEFAULT false,
	"published_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now(),
	CONSTRAINT "videos_slug_en_unique" UNIQUE("slug_en"),
	CONSTRAINT "videos_slug_ar_unique" UNIQUE("slug_ar")
);
--> statement-breakpoint
CREATE TABLE "media_categories" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"is_english" boolean DEFAULT true NOT NULL,
	"is_arabic" boolean DEFAULT true NOT NULL,
	"name_en" text NOT NULL,
	"name_ar" text NOT NULL,
	"slug_en" text NOT NULL,
	"slug_ar" text NOT NULL,
	"description_en" text,
	"description_ar" text,
	"image_url" text,
	"image_alt_en" text,
	"image_alt_ar" text,
	"color" text DEFAULT '#000000',
	"icon" text,
	"page_views" bigint DEFAULT 0,
	"is_published" boolean DEFAULT false,
	"published_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now(),
	CONSTRAINT "media_categories_slug_en_unique" UNIQUE("slug_en"),
	CONSTRAINT "media_categories_slug_ar_unique" UNIQUE("slug_ar")
);
--> statement-breakpoint
ALTER TABLE "projects" ADD CONSTRAINT "projects_program_id_programs_id_fk" FOREIGN KEY ("program_id") REFERENCES "public"."programs"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "videos" ADD CONSTRAINT "videos_category_id_media_categories_id_fk" FOREIGN KEY ("category_id") REFERENCES "public"."media_categories"("id") ON DELETE set null ON UPDATE cascade;