CREATE TABLE "images" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"title_en" text NOT NULL,
	"title_ar" text NOT NULL,
	"description_en" text,
	"description_ar" text,
	"mime_type" text DEFAULT 'image/jpeg' NOT NULL,
	"size" bigint NOT NULL,
	"width" integer NOT NULL,
	"height" integer NOT NULL,
	"url" text NOT NULL,
	"alt" text,
	"location_en" text,
	"location_ar" text,
	"taken_at" timestamp with time zone,
	"photographer" text,
	"is_public" boolean DEFAULT true NOT NULL,
	"program_id" bigint,
	"project_id" bigint,
	"activity_id" bigint,
	"category_id" bigint,
	"slug_en" text NOT NULL,
	"slug_ar" text NOT NULL,
	"keywords_en" text[] DEFAULT '{}',
	"keywords_ar" text[] DEFAULT '{}',
	"tags_en" text[] DEFAULT '{}',
	"tags_ar" text[] DEFAULT '{}',
	"views" bigint DEFAULT 0,
	"is_published" boolean DEFAULT false,
	"published_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now(),
	CONSTRAINT "images_slug_en_unique" UNIQUE("slug_en"),
	CONSTRAINT "images_slug_ar_unique" UNIQUE("slug_ar")
);
